export {MovieCardItem} from '../componets/MovieCardItem/MovieCardItem.tsx'
export {Footer} from '../componets/Footer/Footer.tsx'
export {SearchBar} from '../componets/SearchBar/SearchBar.tsx'
export {SectionTitle} from '../componets/SectionTitle/SectionTitle.tsx'
export {NotFoundPage} from '../componets/NotFoundPage/NotFoundPage.tsx'
export {GlobalSnackbar} from '../componets/GlobalSnackbar/GlobalSnackbar.tsx'
export {TopProgressBar} from '../componets/TopProgressBar/TopProgressBar.tsx'
export {Header} from '../componets/Header/Header.tsx'
